params = {
            'KD': True,
            'MIRLEN': 12,
            'SEQLEN': 12,
            'IN_NODES': 1,
            'OUT_NODES': 1,
            'BASELINE_NODES': 0,
            'HIDDEN1': 2,
            'HIDDEN2': 4,
            'HIDDEN3': 32,
            'STARTING_LEARNING_RATE': 1e-3,
            'ERROR_MODEL': 'l2',
            'NUM_EPOCH': 100,
            'BATCH_SIZE': 200,
            'REPORT_INT': 50,
            'KEEP_PROB_TRAIN': 0.5,
            'TEST_SIZE': 5000,
            # 'RESTORE_FROM': '/lab/bartel4_ata/kathyl/NeuralNet/logdirs/simple/num_matches/1/vars',
            'RESTORE_FROM': None,
        }