all_one_pos:
	python main.py -i ../../data/sean_data/12mers/kds_multinomial_2-5.txt -f /lab/bartel4_ata/kathyl/RNA_Seq/analysis/data/3pseq/for_nn.txt -l ../../logdirs/train_dan_bottleneck1/


all_rnaduplex:
	python main.py -i ../../data/simple/rnaduplex_features.txt -f ../../data/simple/logfc_rnaduplex_features.txt -l ../../logdirs/train_dan_rnaduplex/


